# Generated by Django 5.2.6 on 2025-09-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Enter the student name', max_length=250)),
                ('age', models.IntegerField(help_text='Enter age between 18 to 22')),
                ('dob', models.DateField(help_text='Enter the dob')),
                ('genre', models.CharField(help_text='Genre', max_length=50)),
                ('reg_num', models.IntegerField(help_text='Enter the register.no')),
            ],
        ),
    ]
